language: c
sudo: false
dist: xenial
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
script: bash -ex .travis-opam.sh
env:
  global:
  - TESTS=true
    REVDEPS="ppx_deriving_hardcaml
      ppx_deriving_crowbar
      ppx_deriving_yojson
      ppx_deriving_madcast
      ppx_deriving_protocol
      ppx_deriving_rpc
      ppx_deriving_argparse
      ppx_deriving_cmdliner
      ppx_deriving_protobuf
      ppx_deriving_morphism
      visitors"
  matrix:
  # we require >=4.02.2 but this picks 4.02.3
  - OCAML_VERSION=4.02
  - OCAML_VERSION=4.03
  - OCAML_VERSION=4.04
  - OCAML_VERSION=4.05
  - OCAML_VERSION=4.06
  - OCAML_VERSION=4.07
  - OCAML_VERSION=4.08
  - OCAML_VERSION=4.09
  - OCAML_VERSION=4.10
  - OCAML_VERSION=4.11.0+trunk OCAML_BETA=enable
    PINS="ppx_tools:https://github.com/kit-ty-kate/ppx_tools.git#411
      ppx_deriving_yojson:https://github.com/thierry-martinez/ppx_deriving_yojson.git#411_lightning"
os:
  - linux
