language: c
sudo: false
dist: xenial
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
script: bash -ex .travis-opam.sh
env:
  matrix:
  - REVDEPS=y OCAML_VERSION=4.02 # we require >=4.02.2 but this picks 4.02.3
  - REVDEPS=y OCAML_VERSION=4.03
  - REVDEPS=y OCAML_VERSION=4.04
  - REVDEPS=y OCAML_VERSION=4.05
  - REVDEPS=y OCAML_VERSION=4.06
  - REVDEPS=y OCAML_VERSION=4.07
  - REVDEPS=y OCAML_VERSION=4.08
  - REVDEPS=y OCAML_VERSION=4.09
  - REVDEPS=y OCAML_VERSION=4.10
  - REVDEPS=y OCAML_VERSION=4.11.0+trunk OCAML_BETA=enable
    PINS="ppx_tools:https://github.com/kit-ty-kate/ppx_tools.git#411"
os:
  - linux
